# -*- coding: utf-8 -*-
"""nir210426.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DdS_EprMVIOv861g4D6tpRsqIATDwIj7
"""

import pandas as pd
df = pd.read_csv("/content/Salary Data (2).csv")
df.head()

df.info()

df.isnull().sum()

"""### Imputing Missing Values

I will fill the missing values in the DataFrame. For numerical columns, the mean will be used, and for categorical columns, the mode will be used.
"""

for column in df.columns:
    if df[column].dtype == 'object': # Categorical columns
        mode_value = df[column].mode()[0]
        df[column] = df[column].fillna(mode_value)
    else: # Numerical columns
        mean_value = df[column].mean()
        df[column] = df[column].fillna(mean_value)

# Display the DataFrame info and null counts after imputation
print("\nDataFrame Info after imputation:")
df.info()

print("\nNull values after imputation:")
df.isnull().sum()

"""### Removing Duplicates

I will now check for and remove any duplicate rows in the DataFrame.
"""

print(f"Shape of DataFrame before dropping duplicates: {df.shape}")

duplicates_count = df.duplicated().sum()
if duplicates_count > 0:
    print(f"Found {duplicates_count} duplicate rows. Removing them...")
    df.drop_duplicates(inplace=True)
    print(f"Shape of DataFrame after dropping duplicates: {df.shape}")
else:
    print("No duplicate rows found.")

"""### Applying Label Encoding

I will now apply Label Encoding to the categorical columns to convert them into numerical representations.
"""

from sklearn.preprocessing import LabelEncoder

# Identify categorical columns
categorical_cols = df.select_dtypes(include='object').columns

# Apply Label Encoding
label_encoders = {}
for col in categorical_cols:
    label_encoders[col] = LabelEncoder()
    df[col] = label_encoders[col].fit_transform(df[col])

print("DataFrame after Label Encoding:")
display(df.head())

"""### Separating Input and Output Variables

I will now separate the DataFrame into input features (`X`) and the target variable (`y`). Assuming 'Salary' is the target variable.
"""

X = df.drop('Salary', axis=1)
y = df['Salary']

print("Input features (X) head:")
display(X.head())

print("\nOutput variable (y) head:")
display(y.head())

"""### Splitting Data into Training and Testing Sets

I will now split the input features (`X`) and the target variable (`y`) into training and testing sets. This will allow for proper model evaluation.
"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

"""### Training a Linear Regression Model

I will now train a simple Linear Regression model using the prepared training data.
"""

from sklearn.linear_model import LinearRegression

# Initialize the Linear Regression model
linear_reg_model = LinearRegression()

# Train the model using the training data
linear_reg_model.fit(X_train, y_train)

print("Linear Regression model trained successfully.")

"""### Training a Decision Tree Regressor Model

I will now train a Decision Tree Regressor model using the prepared training data.
"""

from sklearn.tree import DecisionTreeRegressor

# Initialize the Decision Tree Regressor model
decision_tree_model = DecisionTreeRegressor(random_state=42)

# Train the model using the training data
decision_tree_model.fit(X_train, y_train)

print("Decision Tree Regressor model trained successfully.")

"""### Training a Random Forest Regressor Model

I will now train a Random Forest Regressor model using the prepared training data.
"""

from sklearn.ensemble import RandomForestRegressor

# Initialize the Random Forest Regressor model
random_forest_model = RandomForestRegressor(random_state=42)

# Train the model using the training data
random_forest_model.fit(X_train, y_train)

print("Random Forest Regressor model trained successfully.")

"""### Training a Support Vector Machine (SVM) Model

I will now train a Support Vector Machine (SVM) model using the prepared training data.
"""

from sklearn.svm import SVR

# Initialize the Support Vector Regressor model
svm_model = SVR(kernel='rbf') # RBF kernel is a common choice for regression

# Train the model using the training data
svm_model.fit(X_train, y_train)

print("Support Vector Machine (SVM) model trained successfully.")

"""### Training a K-Nearest Neighbors (KNN) Regressor Model

I will now train a K-Nearest Neighbors (KNN) Regressor model using the prepared training data.
"""

from sklearn.neighbors import KNeighborsRegressor

# Initialize the K-Nearest Neighbors Regressor model
knn_model = KNeighborsRegressor(n_neighbors=5) # n_neighbors is a key parameter for KNN

# Train the model using the training data
knn_model.fit(X_train, y_train)

print("K-Nearest Neighbors (KNN) Regressor model trained successfully.")

"""### Model Evaluation and Comparison

I will now evaluate the performance of each trained model using the test set (`X_test`, `y_test`) and compare them using metrics like R-squared and Mean Absolute Error (MAE).
"""

from sklearn.metrics import r2_score, mean_absolute_error
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Dictionary to store model predictions and performance metrics
predictions = {}
metrics = []

models = {
    'Linear Regression': linear_reg_model,
    'Decision Tree': decision_tree_model,
    'Random Forest': random_forest_model,
    'SVM': svm_model,
    'KNN': knn_model
}

for name, model in models.items():
    # Make predictions
    y_pred = model.predict(X_test)
    predictions[name] = y_pred

    # Calculate R-squared and MAE
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    metrics.append({'Model': name, 'R-squared': r2, 'MAE': mae})

# Convert metrics to a DataFrame for easy viewing
metrics_df = pd.DataFrame(metrics)

print("Model Performance Metrics:")
display(metrics_df.round(3))

"""#### Visualization of Model Performance"""

# Plotting R-squared
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

sns.barplot(x='Model', y='R-squared', data=metrics_df.sort_values(by='R-squared', ascending=False), ax=axes[0], palette='viridis')
axes[0].set_title('Model R-squared Comparison')
axes[0].set_ylabel('R-squared Score')
axes[0].tick_params(axis='x', rotation=45)

# Plotting MAE
sns.barplot(x='Model', y='MAE', data=metrics_df.sort_values(by='MAE'), ax=axes[1], palette='magma')
axes[1].set_title('Model Mean Absolute Error (MAE) Comparison')
axes[1].set_ylabel('Mean Absolute Error')
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

"""### Saving the Best Model

Based on the evaluation, the Random Forest Regressor performed the best. I will now save this model in `pkl` format for future use.
"""

import pickle

# Assuming random_forest_model is the best model based on previous evaluation
best_model = random_forest_model

# Define the filename for saving the model
model_filename = 'random_forest_model.pkl'

# Save the model to a .pkl file
with open(model_filename, 'wb') as file:
    pickle.dump(best_model, file)

print(f"Best model (Random Forest Regressor) saved successfully as '{model_filename}'")



